fix(workflows): update kind-localsetup.yaml to improve debugging steps and comment out unnecessary commands
On-behalf-of: @SAP angel.kafazov@sap.com
Signed-off-by: Angel Kafazov <akafazov@cst-bg.net>

diff --git a/.github/workflows/kind-localsetup.yaml b/.github/workflows/kind-localsetup.yaml
--- a/.github/workflows/kind-localsetup.yaml
+++ b/.github/workflows/kind-localsetup.yaml
@@ -74,98 +74,108 @@ jobs:
     #     docker login ghcr.io -u ${{ github.repository_owner }} -p ${{ steps.generate-token.outputs.token }}
     #     docker pull ghcr.io/openmfp/portal:0.287.0
 
-    # Step 6: Run start.sh
-    - name: Run start.sh
-      id: run_start_sh
-      env:
-        GH_TOKEN: ${{ steps.generate-token.outputs.token }}
-        GH_USER: ${{ github.repository_owner }}
-        DEBUG: true
-      run: |
-        chmod +x ./local-setup/scripts/start.sh
-        ./local-setup/scripts/start.sh
-      continue-on-error: true
+    # # Step 6: Run start.sh
+    # - name: Run start.sh
+    #   id: run_start_sh
+    #   env:
+    #     GH_TOKEN: ${{ steps.generate-token.outputs.token }}
+    #     GH_USER: ${{ github.repository_owner }}
+    #     DEBUG: true
+    #   run: |
+    #     chmod +x ./local-setup/scripts/start.sh
+    #     ./local-setup/scripts/start.sh
+    #   continue-on-error: true
 
-    # debug step 6
-    - name: Debug6
-      if: steps.run_start_sh.outcome == 'failure'
+    # Debug token with docker
+    - name: Debug token with docker
       run: |
         set -x
-        docker ps
-        curl -s -i http://localhost:8000/ || true
-
-        kubectl get pods -A -o wide
-        kubectl get svc -A
-        kubectl get helmreleases -A
-        kubectl get deployments -A
-        kubectl get secrets -A
-        kubectl get crds -A
-        kubectl get nodes -o wide
-
-        echo "Describe all pods which are not Running"
-        kubectl get pods -A --field-selector=status.phase!=Running -o jsonpath='{range .items[*]}{.metadata.namespace} {.metadata.name}{"\n"}{end}' | while read namespace name; do kubectl describe pod $name -n $namespace; done
-
-        echo "Describe all helmreleases which are not Ready yet"
-        kubectl get helmreleases -A -o json | jq -r '.items[] | select(.status.conditions[]? | select(.type == "Ready" and .status != "True")) | "\(.metadata.namespace) \(.metadata.name)"' | while read namespace name; do kubectl describe helmrelease $name -n $namespace; done
-
-        echo "Print imagePullSecret"
-        kubectl get secret ghcr-credentials -n openmfp-system -o yaml
-
-        echo "Test docker login and pull"
+        echo ${{ steps.generate-token.outputs.token }}
         docker login ghcr.io -u ${{ github.repository_owner }} -p ${{ steps.generate-token.outputs.token }}
         docker pull ghcr.io/openmfp/portal:0.287.0
 
+        curl -H "Authorization: Bearer ${{ steps.generate-token.outputs.token }}" https://api.github.com/user
 
-    # Step 7: Prepare the NodeJS/playwright environment
-    - name: Cache node modules
-      uses: actions/cache@v3
-      with:
-        path: ~/node_modules
-        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
-        restore-keys: |
-          ${{ runner.os }}-node-
+    # # debug step 6
+    # - name: Debug6
+    #   if: steps.run_start_sh.outcome == 'failure'
+    #   run: |
+    #     set -x
+    #     docker ps
+    #     curl -s -i http://localhost:8000/ || true
 
-    # Step 8: Install NodeJS and dependencies
-    - name: Node ${{ matrix.node-version }}
-      uses: actions/setup-node@v3
-      with:
-        node-version: ${{ matrix.node-version }}
-        cache: 'npm'
-        cache-dependency-path: 'local-setup/e2e'
+    #     kubectl get pods -A -o wide
+    #     kubectl get svc -A
+    #     kubectl get helmreleases -A
+    #     kubectl get deployments -A
+    #     kubectl get secrets -A
+    #     kubectl get crds -A
+    #     kubectl get nodes -o wide
 
-    # Step 9: Install npm dependencies
-    - name: Clean install of npm dependencies
-      run: |
-        cd local-setup/e2e
-        npm install
-        npm ci
-        npx playwright install 
+    #     echo "Describe all pods which are not Running"
+    #     kubectl get pods -A --field-selector=status.phase!=Running -o jsonpath='{range .items[*]}{.metadata.namespace} {.metadata.name}{"\n"}{end}' | while read namespace name; do kubectl describe pod $name -n $namespace; done
 
-    # Step 10: Run the end-to-end tests
-    - name: End2End tests
-      run: |
-        sleep 10
+    #     echo "Describe all helmreleases which are not Ready yet"
+    #     kubectl get helmreleases -A -o json | jq -r '.items[] | select(.status.conditions[]? | select(.type == "Ready" and .status != "True")) | "\(.metadata.namespace) \(.metadata.name)"' | while read namespace name; do kubectl describe helmrelease $name -n $namespace; done
 
-        kubectl get pods -A
-        kubectl get svc -A
+    #     echo "Print imagePullSecret"
+    #     kubectl get secret ghcr-credentials -n openmfp-system -o yaml
 
-        # debug commands
-        docker ps
-        echo "Waiting for the service to be ready..."
-        for i in {1..30}; do
-          curl -s http://localhost:8000/ > /dev/null || true
-          if [ $? -eq 0 ]; then
-            echo "Service is ready."
-            sleep 50
-            break
-          fi
-          echo "Service not ready, retrying in 2 seconds..."
-          sleep 2
-        done
+    #     echo "Test docker login and pull"
+    #     docker login ghcr.io -u ${{ github.repository_owner }} -p ${{ steps.generate-token.outputs.token }}
+    #     docker pull ghcr.io/openmfp/portal:0.287.0
 
-        curl -s -i http://localhost:8000/ || true
 
-        echo "Running sample test"
-        node local-setup/e2e/test-example.js
-        echo "Running e2e tests"
-        node local-setup/e2e/test-register-and-navigate.js
+    # # Step 7: Prepare the NodeJS/playwright environment
+    # - name: Cache node modules
+    #   uses: actions/cache@v3
+    #   with:
+    #     path: ~/node_modules
+    #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
+    #     restore-keys: |
+    #       ${{ runner.os }}-node-
+
+    # # Step 8: Install NodeJS and dependencies
+    # - name: Node ${{ matrix.node-version }}
+    #   uses: actions/setup-node@v3
+    #   with:
+    #     node-version: ${{ matrix.node-version }}
+    #     cache: 'npm'
+    #     cache-dependency-path: 'local-setup/e2e'
+
+    # # Step 9: Install npm dependencies
+    # - name: Clean install of npm dependencies
+    #   run: |
+    #     cd local-setup/e2e
+    #     npm install
+    #     npm ci
+    #     npx playwright install 
+
+    # # Step 10: Run the end-to-end tests
+    # - name: End2End tests
+    #   run: |
+    #     sleep 10
+
+    #     kubectl get pods -A
+    #     kubectl get svc -A
+
+    #     # debug commands
+    #     docker ps
+    #     echo "Waiting for the service to be ready..."
+    #     for i in {1..30}; do
+    #       curl -s http://localhost:8000/ > /dev/null || true
+    #       if [ $? -eq 0 ]; then
+    #         echo "Service is ready."
+    #         sleep 50
+    #         break
+    #       fi
+    #       echo "Service not ready, retrying in 2 seconds..."
+    #       sleep 2
+    #     done
+
+    #     curl -s -i http://localhost:8000/ || true
+
+    #     echo "Running sample test"
+    #     node local-setup/e2e/test-example.js
+    #     echo "Running e2e tests"
+    #     node local-setup/e2e/test-register-and-navigate.js
