test token

diff --git a/.github/workflows/kind-localsetup.yaml b/.github/workflows/kind-localsetup.yaml
--- a/.github/workflows/kind-localsetup.yaml
+++ b/.github/workflows/kind-localsetup.yaml
@@ -59,66 +59,74 @@ jobs:
           extension-manager-operator
           portal
 
-    # Step 6: Run start.sh
-    - name: Run start.sh
-      env:
-        GH_TOKEN: ${{ steps.generate-token.outputs.token }}
-        GH_USER: ${{ github.repository_owner }}
-        DEBUG: true
+    # Debug step: test docker pull
+    - name: Test docker pull
+      GH_TOKEN: ${{ steps.generate-token.outputs.token }}
+      GH_USER: ${{ github.repository_owner }}
       run: |
-        chmod +x ./local-setup/scripts/start.sh
-        ./local-setup/scripts/start.sh
+        docker login ghcr.io -u $GH_USER -p $GH_TOKEN
+        docker pull ghcr.io/openmfp/portal:0.287.0
 
-    # Step 7: Prepare the NodeJS/playwright environment
-    - name: Cache node modules
-      uses: actions/cache@v3
-      with:
-        path: ~/node_modules
-        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
-        restore-keys: |
-          ${{ runner.os }}-node-
+    # # Step 6: Run start.sh
+    # - name: Run start.sh
+    #   env:
+    #     GH_TOKEN: ${{ steps.generate-token.outputs.token }}
+    #     GH_USER: ${{ github.repository_owner }}
+    #     DEBUG: true
+    #   run: |
+    #     chmod +x ./local-setup/scripts/start.sh
+    #     ./local-setup/scripts/start.sh
 
-    # Step 8: Install NodeJS and dependencies
-    - name: Node ${{ matrix.node-version }}
-      uses: actions/setup-node@v3
-      with:
-        node-version: ${{ matrix.node-version }}
-        cache: 'npm'
-        cache-dependency-path: 'local-setup/e2e'
+    # # Step 7: Prepare the NodeJS/playwright environment
+    # - name: Cache node modules
+    #   uses: actions/cache@v3
+    #   with:
+    #     path: ~/node_modules
+    #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
+    #     restore-keys: |
+    #       ${{ runner.os }}-node-
 
-    # Step 9: Install npm dependencies
-    - name: Clean install of npm dependencies
-      run: |
-        cd local-setup/e2e
-        npm install
-        npm ci
-        npx playwright install 
+    # # Step 8: Install NodeJS and dependencies
+    # - name: Node ${{ matrix.node-version }}
+    #   uses: actions/setup-node@v3
+    #   with:
+    #     node-version: ${{ matrix.node-version }}
+    #     cache: 'npm'
+    #     cache-dependency-path: 'local-setup/e2e'
 
-    # Step 10: Run the end-to-end tests
-    - name: End2End tests
-      run: |
-        sleep 10
+    # # Step 9: Install npm dependencies
+    # - name: Clean install of npm dependencies
+    #   run: |
+    #     cd local-setup/e2e
+    #     npm install
+    #     npm ci
+    #     npx playwright install 
 
-        kubectl get pods -A
-        kubectl get svc -A
+    # # Step 10: Run the end-to-end tests
+    # - name: End2End tests
+    #   run: |
+    #     sleep 10
 
-        # debug commands
-        docker ps
-        echo "Waiting for the service to be ready..."
-        for i in {1..30}; do
-          curl -s http://localhost:8000/ > /dev/null || true
-          if [ $? -eq 0 ]; then
-            echo "Service is ready."
-            sleep 50
-            break
-          fi
-          echo "Service not ready, retrying in 2 seconds..."
-          sleep 2
-        done
+    #     kubectl get pods -A
+    #     kubectl get svc -A
 
-        curl -s -i http://localhost:8000/ || true
+    #     # debug commands
+    #     docker ps
+    #     echo "Waiting for the service to be ready..."
+    #     for i in {1..30}; do
+    #       curl -s http://localhost:8000/ > /dev/null || true
+    #       if [ $? -eq 0 ]; then
+    #         echo "Service is ready."
+    #         sleep 50
+    #         break
+    #       fi
+    #       echo "Service not ready, retrying in 2 seconds..."
+    #       sleep 2
+    #     done
 
-        echo "Running sample test"
-        node local-setup/e2e/test-example.js
-        echo "Running e2e tests"
-        node local-setup/e2e/test-register-and-navigate.js
+    #     curl -s -i http://localhost:8000/ || true
+
+    #     echo "Running sample test"
+    #     node local-setup/e2e/test-example.js
+    #     echo "Running e2e tests"
+    #     node local-setup/e2e/test-register-and-navigate.js
